### ISSUE TITLE
Improve support for string filter types

### ISSUE THREAD

**Issue by nt1m** [mdibaiee/CSS-Filter-Tooltip#3]
The support I added is still quite buggy since the string returned by css() have undefined in it.
I think there's a parser going through the string, but I haven't figured out where.

**Comment by mdibaiee** [comment]
I will look into this asap

**Comment by mdibaiee** [comment]
This was fixed in [341af366](https://github.com/mdibaiee/CSS-Filter-Tooltip/commit/341af366ecd70f62c18af49758bcd5c80a3181e4)
